local tts = require("tts")
vim.api.nvim_create_user_command("TTSStart", tts.start)
vim.api.nvim_create_user_command("TTSStop", tts.stop)
vim.api.nvim_create_user_command("TTSPush", tts.push)
vim.api.nvim_create_user_command("TTSPull", tts.pull)
vim.api.nvim_create_user_command("TTSCreateProject", tts.create_project)
vim.api.nvim_create_user_command("TTSScan", tts.scan_project)
vim.api.nvim_create_user_command("TTSExec", function(args)
	tts.exec_lua_code(unpack(args.args))
end, { nargs = 2 })
